### PR TITLE
1.12.1 update, added icons, fixed messages, additional dropdown issues

### PR DESCRIPTION
**Pull request by joryphillips**
When I updated to Semantic UI 1.12.1, some things broke for me. This spurred some effort on my part to fix some more things. I have obviously made some opinionated decisions about icons, menu spacing,
etc… but I did also fix the problem with the changed password success message! I also tested and fixed similar problems with the email only login functions.

Obviously... take or leave some of my design decisions as you see fit, and let me know what you think!

### CODE REVIEW

**Comment by joryphillips** [comment]
Here's an example of what 1.12.1 was doing prior to these changes:
before

And here is an example of the fix, and addition of icons:
after

**Comment by iandfox** [comment]
Sorry for the late reply.. I'm getting married in 5 days and have been pretty busy! :)

So looks like there's 0 padding at the top when you have a 3rd party service set up - which is weird, because the menu still has the same padding, it's like that first `.item` is just ignoring it!  
screen shot 2015-05-20 at 9 28 06 am

Also, apparently Semantic is updating to 2.0 on June 1st, so hopefully most of the markup remains the same...

Also also, preserving this for posterity:  
Checked Semantic site to see the release notes for the latest versions, and it looks like someone installed a social sharing plugin wrong, or something :D  
screen shot 2015-05-20 at 9 30 15 am

**Comment by iandfox** [comment]
The rest looks good though - I'm going to go ahead and merge this in, and then work on getting it pushed up to atmosphere.

Thanks a lot! :)

**Comment by joryphillips** [comment]
Wow, congratulations!! Have a great wedding. I'll work on fixing the 3rd party stuff in the meantime .

**Comment by joryphillips** [comment]
P.S. I've seen the Semantic site do that before, too -- they must have a problem with a resource not loading from time to time, or something!

**Comment by joryphillips** [comment]
P.P.S, this is what the 1.12.1 changelog says:  

> Dropdown - Fixes issue with chained dropdown methods used on a <select> not applying to the generated ui dropdown _Backport from 2.0_   

Hopefully that last part means we'll be golden for 2.0!    

I looked at the dropdown change made in detail. It was in the javascript, and is noted as _"invoke method in context of current instance."_    

1.12.2 also made some fixes to Dropdown, but I've seen no additional issues with it.
(edit: the internet is broken today. I can't make markdown work correctly.)

**Pull request merged**
